// Generates src/generated/{abis,deployments}.ts from Forge's build output and contracts/deployments.
// Run after `forge build` or a deploy: pnpm --filter @symbolon/chain generate
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

const contracts = fileURLToPath(new URL("../../../contracts/", import.meta.url));
const out = fileURLToPath(new URL("../src/generated/", import.meta.url));

/** Contract name → artifact path under contracts/out */
const ARTIFACTS: Record<string, string> = {
  invoiceLedger: "InvoiceLedger.sol/InvoiceLedger.json",
  symbolonVault: "SymbolonVault.sol/SymbolonVault.json",
  vaultFactory: "VaultFactory.sol/VaultFactory.json",
  releaseRegistry: "ReleaseRegistry.sol/ReleaseRegistry.json",
  vaultLens: "VaultLens.sol/VaultLens.json",
  usycTeller: "IUsycTeller.sol/IUsycTeller.json",
  usycEntitlements: "IUsycTeller.sol/IUsycEntitlements.json",
  erc20: "IERC20Metadata.sol/IERC20Metadata.json",
  tokenMessengerV2: "ITokenMessengerV2.sol/ITokenMessengerV2.json",
};

const HEADER = "// Generated by packages/chain/scripts/generate.ts. Do not edit.\n";

export function generateAbis(): string {
  let src = HEADER;
  for (const [name, path] of Object.entries(ARTIFACTS)) {
    const file = `${contracts}out/${path}`;
    if (!existsSync(file)) throw new Error(`missing ${file}: run \`forge build\` in contracts/`);
    const { abi } = JSON.parse(readFileSync(file, "utf8"));
    src += `\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  }
  return src;
}

export function generateDeployments(): string {
  const dir = `${contracts}deployments/`;
  const chains = readdirSync(dir).filter((f) => /^\d+\.json$/.test(f));
  const registry: Record<string, unknown> = {};
  for (const file of chains) {
    const chainId = file.replace(".json", "");
    const deployment = JSON.parse(readFileSync(`${dir}${file}`, "utf8"));
    const external = JSON.parse(readFileSync(`${dir}external/${file}`, "utf8"));
    registry[chainId] = { ...deployment, externalConfig: external };
  }
  return `${HEADER}\nexport const deployments = ${JSON.stringify(registry, null, 2)} as const;\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(`${out}abis.ts`, generateAbis());
  writeFileSync(`${out}deployments.ts`, generateDeployments());
  console.log(`wrote ${out}abis.ts and ${out}deployments.ts`);
}
