import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { getAddress, keccak256, stringToBytes } from "viem";

const contracts = fileURLToPath(new URL("../../../contracts/", import.meta.url));
const out = fileURLToPath(new URL("../src/generated/", import.meta.url));

/** Contract name → artifact path under contracts/out */
const ARTIFACTS: Record<string, string> = {
  invoiceLedger: "InvoiceLedger.sol/InvoiceLedger.json",
  symbolonVault: "SymbolonVault.sol/SymbolonVault.json",
  vaultFactory: "VaultFactory.sol/VaultFactory.json",
  releaseRegistry: "ReleaseRegistry.sol/ReleaseRegistry.json",
  vaultLens: "VaultLens.sol/VaultLens.json",
  usycTeller: "IUsycTeller.sol/IUsycTeller.json",
  usycEntitlements: "IUsycTeller.sol/IUsycEntitlements.json",
  erc20: "IERC20Metadata.sol/IERC20Metadata.json",
  tokenMessengerV2: "ITokenMessengerV2.sol/ITokenMessengerV2.json",
};

const HEADER = "// Generated by packages/chain/scripts/generate.ts. Do not edit.\n";

export function generateAbis(): string {
  let src = HEADER;
  for (const [name, path] of Object.entries(ARTIFACTS)) {
    const file = `${contracts}out/${path}`;
    if (!existsSync(file)) throw new Error(`missing ${file}: run \`forge build\` in contracts/`);
    const { abi } = JSON.parse(readFileSync(file, "utf8"));
    src += `\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  }
  return src;
}

export function generateDeployments(): string {
  const dir = `${contracts}deployments/`;
  const chains = readdirSync(dir).filter((f) => /^\d+\.json$/.test(f));
  const registry: Record<string, unknown> = {};
  for (const file of chains) {
    const chainId = file.replace(".json", "");
    const deployment = JSON.parse(readFileSync(`${dir}${file}`, "utf8"));
    const external = JSON.parse(readFileSync(`${dir}external/${file}`, "utf8"));
    registry[chainId] = { ...deployment, externalConfig: external };
  }
  return `${HEADER}\nexport const deployments = ${JSON.stringify(registry, null, 2)} as const;\n`;
}

export function generateReleases(): string {
  const dir = `${contracts}deployments/releases/`;
  if (!existsSync(dir)) {
    return `${HEADER}\nexport const releases = {} as const;\n`;
  }
  const files = readdirSync(dir).filter((f) => /^\d+-v\d+\.json$/.test(f)).sort();
  const rels: Record<string, {
    chainId: number;
    version: number;
    implementation: string;
    factory: string;
    startBlock: number;
    notesHash: string;
    notes: string;
  }> = {};

  for (const file of files) {
    const chainId = parseInt(file.slice(0, file.indexOf("-v")), 10);
    const content = JSON.parse(readFileSync(`${dir}${file}`, "utf8"));
    const implementation = getAddress(content.SymbolonVaultImplementation);
    const version = Number(content.version);
    const notesHash = (content.notesHash as string).toLowerCase();
    const notesFile = `${contracts}${content.notes}`;
    if (!existsSync(notesFile)) {
      throw new Error(`missing release notes file: ${notesFile}`);
    }
    const notesText = readFileSync(notesFile, "utf8");
    const computedHash = keccak256(stringToBytes(notesText)).toLowerCase();
    if (computedHash !== notesHash) {
      throw new Error(
        `release notes hash mismatch for ${file}: expected ${notesHash}, computed ${computedHash}`
      );
    }
    rels[implementation] = {
      chainId,
      version,
      implementation,
      // each release has its own factory (a factory's implementation is immutable), and Vaults made by an older one still exist
      factory: getAddress(content.VaultFactory),
      startBlock: Number(content.startBlock),
      notesHash: content.notesHash,
      notes: notesText,
    };
  }

  return `${HEADER}\nexport interface ReleaseInfo {\n  chainId: number;\n  version: number;\n  implementation: \`0x\${string}\`;\n  factory: \`0x\${string}\`;\n  startBlock: number;\n  notesHash: \`0x\${string}\`;\n  notes: string;\n}\n\nexport const releases = ${JSON.stringify(rels, null, 2)} as const;\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(`${out}abis.ts`, generateAbis());
  writeFileSync(`${out}deployments.ts`, generateDeployments());
  writeFileSync(`${out}releases.ts`, generateReleases());
  console.log(`wrote ${out}abis.ts, ${out}deployments.ts, and ${out}releases.ts`);
}
