// SPDX-License-Identifier: MIT
pragma solidity 0.8.36;

import {Test} from "forge-std/Test.sol";

import {
    Invoice,
    EarlyPayTier,
    EarlyPayOffer,
    Cancel,
    CreditNote,
    PayoutChange,
    SealRotation,
    Approval,
    DiscountKind,
    DiscountProof
} from "../src/types/SealTypes.sol";
import {IInvoiceLedger} from "../src/interfaces/IInvoiceLedger.sol";
import {InvoiceLedger} from "../src/InvoiceLedger.sol";
import {MockERC20} from "./mocks/MockERC20.sol";
import {MockTokenMessenger} from "./mocks/MockTokenMessenger.sol";
import {SealTypesHarness} from "./harness/SealTypesHarness.sol";

/// @notice Checks the known vectors generated by packages/seal (TypeScript) against the contracts: every struct hash,
/// digest and fingerprint, byte-identical signatures, and real settlements using the TypeScript signatures.
contract SealVectorsTest is Test {
    string internal constant VECTORS = "../packages/seal/vectors/v1.json";
    uint256 internal constant PAYER_FUNDS = 1e15;

    string internal json;
    InvoiceLedger internal ledger;
    MockERC20 internal token;
    MockTokenMessenger internal messenger;
    SealTypesHarness internal harness;
    address internal payer = makeAddr("payer");

    function setUp() public {
        // read-only, scoped to the vectors directory by fs_permissions
        // forge-lint: disable-next-line(unsafe-cheatcode)
        json = vm.readFile(VECTORS);
        // the domain separator is cached at construction, so the chain must be set first
        vm.chainId(vm.parseJsonUint(json, ".domain.chainId"));
        vm.warp(vm.parseJsonUint(json, ".now"));

        messenger = new MockTokenMessenger();
        harness = new SealTypesHarness();
        uint32 localDomain = uint32(vm.parseJsonUint(json, ".localDomain"));
        deployCodeTo(
            "InvoiceLedger.sol:InvoiceLedger", abi.encode(address(messenger), localDomain), _labelAddress("ledger")
        );
        deployCodeTo(
            "MockERC20.sol:MockERC20",
            abi.encode("USD Coin", "USDC", uint8(vm.parseJsonUint(json, ".tokenDecimals"))),
            _labelAddress("token")
        );
        ledger = InvoiceLedger(_labelAddress("ledger"));
        token = MockERC20(_labelAddress("token"));

        token.mint(payer, PAYER_FUNDS);
        vm.prank(payer);
        token.approve(address(ledger), type(uint256).max);
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Derivations and hashes
    // ---------------------------------------------------------------------------------------------------------------

    function test_vectors_addressesDeriveFromLabels() public view {
        assertEq(address(ledger), vm.parseJsonAddress(json, ".addresses.ledger"));
        assertEq(address(ledger), vm.parseJsonAddress(json, ".domain.verifyingContract"));
        assertEq(address(token), vm.parseJsonAddress(json, ".addresses.token"));
        assertEq(_labelAddress("payout"), vm.parseJsonAddress(json, ".addresses.payout"));
        assertEq(_labelAddress("remotePayout"), vm.parseJsonAddress(json, ".addresses.remotePayout"));
        assertEq(_labelAddress("vault"), vm.parseJsonAddress(json, ".addresses.vault"));
        assertEq(vm.addr(_key("seal")), vm.parseJsonAddress(json, ".addresses.seal"));
        assertEq(vm.addr(_key("approver")), vm.parseJsonAddress(json, ".addresses.approver"));
    }

    function test_vectors_domainMatchesLedger() public view {
        bytes32 expected = keccak256(
            abi.encode(
                keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),
                keccak256(bytes(vm.parseJsonString(json, ".domain.name"))),
                keccak256(bytes(vm.parseJsonString(json, ".domain.version"))),
                block.chainid,
                address(ledger)
            )
        );
        assertEq(ledger.domainSeparator(), expected);
    }

    function test_vectors_invoicesMatchLedger() public view {
        string[3] memory names = ["plain", "curve", "crossChain"];
        for (uint256 i; i < names.length; ++i) {
            string memory base = string.concat(".invoices.", names[i]);
            Invoice memory inv = _invoice(names[i]);
            bytes32 fp = vm.parseJsonBytes32(json, string.concat(base, ".fingerprint"));

            assertEq(harness.hashInvoice(inv), vm.parseJsonBytes32(json, string.concat(base, ".structHash")), names[i]);
            assertEq(ledger.fingerprint(inv), fp, names[i]);
            assertEq(ledger.hashTypedData(harness.hashInvoice(inv)), fp, names[i]);
            // documentHash is keccak256 of the canonical document bytes the TS side hashed
            assertEq(
                keccak256(bytes(vm.parseJsonString(json, string.concat(base, ".document")))), inv.documentHash, names[i]
            );
            _assertSignature(_key("seal"), fp, vm.parseJsonBytes(json, string.concat(base, ".signature")), names[i]);
        }
    }

    function test_vectors_messagesMatchLedger() public view {
        _checkMessage("offer", harness.hashOffer(_offer()), _key("seal"));
        _checkMessage(
            "cancel",
            harness.hashCancel(Cancel({fingerprint: _bytes32(".messages.cancel.message.fingerprint")})),
            _key("seal")
        );
        _checkMessage(
            "creditNote",
            harness.hashCreditNote(
                CreditNote({
                    fingerprint: _bytes32(".messages.creditNote.message.fingerprint"),
                    amount: _uint(".messages.creditNote.message.amount"),
                    documentHash: _bytes32(".messages.creditNote.message.documentHash"),
                    nonce: uint64(_uint(".messages.creditNote.message.nonce"))
                })
            ),
            _key("seal")
        );
        _checkMessage(
            "payoutChange",
            harness.hashPayoutChange(
                PayoutChange({
                    seal: _address(".messages.payoutChange.message.seal"),
                    newPayout: _address(".messages.payoutChange.message.newPayout"),
                    payoutDomain: uint32(_uint(".messages.payoutChange.message.payoutDomain")),
                    nonce: uint64(_uint(".messages.payoutChange.message.nonce"))
                })
            ),
            _key("seal")
        );
        _checkMessage(
            "sealRotation",
            harness.hashSealRotation(
                SealRotation({
                    oldSeal: _address(".messages.sealRotation.message.oldSeal"),
                    newSeal: _address(".messages.sealRotation.message.newSeal"),
                    nonce: uint64(_uint(".messages.sealRotation.message.nonce"))
                })
            ),
            _key("seal")
        );
        _checkMessage(
            "approval",
            harness.hashApproval(
                Approval({
                    vault: _address(".messages.approval.message.vault"),
                    fingerprint: _bytes32(".messages.approval.message.fingerprint"),
                    credit: _uint(".messages.approval.message.credit"),
                    deadline: uint64(_uint(".messages.approval.message.deadline"))
                })
            ),
            _key("approver")
        );
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Settlements with TypeScript signatures
    // ---------------------------------------------------------------------------------------------------------------

    function test_vectors_settlePlain() public {
        _settle(0);
    }

    function test_vectors_settleCurveTier() public {
        _settle(1);
    }

    function test_vectors_settleCurveOffer() public {
        _settle(2);
    }

    function test_vectors_settleCrossChain() public {
        _settle(3);
    }

    function test_vectors_settledInvoiceCantBePaidAgain() public {
        _settle(0);
        Invoice memory inv = _invoice("plain");
        bytes memory sig = vm.parseJsonBytes(json, ".invoices.plain.signature");
        DiscountProof memory none;
        bytes32 fp = ledger.fingerprint(inv);
        vm.prank(payer);
        vm.expectRevert(abi.encodeWithSelector(IInvoiceLedger.OverCredit.selector, fp, 0, 1));
        ledger.settle(inv, sig, 1, none, 0);
    }

    function _settle(uint256 index) internal {
        string memory base = string.concat(".settlements[", vm.toString(index), "]");
        string memory name = vm.parseJsonString(json, string.concat(base, ".invoice"));
        string memory kind = vm.parseJsonString(json, string.concat(base, ".discount"));
        uint256 credit = _uint(string.concat(base, ".credit"));
        uint256 maxFee = _uint(string.concat(base, ".maxFee"));
        uint256 expectedPaid = _uint(string.concat(base, ".paid"));

        Invoice memory inv = _invoice(name);
        bytes memory sealSig = vm.parseJsonBytes(json, string.concat(".invoices.", name, ".signature"));
        DiscountProof memory discount;
        if (keccak256(bytes(kind)) == keccak256("tier")) {
            discount.kind = DiscountKind.Tier;
            discount.tierIndex = _uint(string.concat(base, ".tierIndex"));
        } else if (keccak256(bytes(kind)) == keccak256("offer")) {
            EarlyPayOffer memory offer = _offer();
            discount.kind = DiscountKind.Offer;
            discount.offerBps = offer.discountBps;
            discount.offerValidUntil = offer.validUntil;
            discount.offerSig = vm.parseJsonBytes(json, ".messages.offer.signature");
        }

        uint256 payerBefore = token.balanceOf(payer);
        uint256 payoutBefore = token.balanceOf(inv.payoutAddress);
        uint256 messengerBefore = token.balanceOf(address(messenger));

        vm.prank(payer);
        uint256 paid = ledger.settle(inv, sealSig, credit, discount, maxFee);

        assertEq(paid, expectedPaid, "paid matches the TypeScript quote");
        assertEq(payerBefore - token.balanceOf(payer), paid + maxFee, "payer charged");
        if (inv.payoutDomain == ledger.localDomain()) {
            assertEq(token.balanceOf(inv.payoutAddress) - payoutBefore, paid, "vendor paid locally");
        } else {
            assertEq(token.balanceOf(address(messenger)) - messengerBefore, paid + maxFee, "burned for CCTP");
        }
        assertEq(ledger.remaining(ledger.fingerprint(inv)), inv.amount - credit);
    }

    // ---------------------------------------------------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------------------------------------------------

    function _checkMessage(string memory name, bytes32 structHash, uint256 key) internal view {
        string memory base = string.concat(".messages.", name);
        assertEq(structHash, _bytes32(string.concat(base, ".structHash")), name);
        bytes32 digest = ledger.hashTypedData(structHash);
        assertEq(digest, _bytes32(string.concat(base, ".digest")), name);
        assertEq(vm.addr(key), _address(string.concat(base, ".signer")), name);
        _assertSignature(key, digest, vm.parseJsonBytes(json, string.concat(base, ".signature")), name);
    }

    /// @notice RFC 6979 makes signatures deterministic, so Foundry must reproduce the TypeScript bytes exactly
    function _assertSignature(uint256 key, bytes32 digest, bytes memory sig, string memory name) internal pure {
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(key, digest);
        assertEq(sig, abi.encodePacked(r, s, v), name);
        assertEq(ecrecover(digest, v, r, s), vm.addr(key), name);
    }

    function _invoice(string memory name) internal view returns (Invoice memory inv) {
        string memory base = string.concat(".invoices.", name, ".invoice");
        inv.seal = _address(string.concat(base, ".seal"));
        inv.token = _address(string.concat(base, ".token"));
        inv.amount = _uint(string.concat(base, ".amount"));
        inv.issuedAt = uint64(_uint(string.concat(base, ".issuedAt")));
        inv.dueDate = uint64(_uint(string.concat(base, ".dueDate")));
        inv.payoutAddress = _address(string.concat(base, ".payoutAddress"));
        inv.payoutDomain = uint32(_uint(string.concat(base, ".payoutDomain")));
        inv.payerRef = _bytes32(string.concat(base, ".payerRef"));
        inv.invoiceNumberHash = _bytes32(string.concat(base, ".invoiceNumberHash"));
        inv.poRef = _bytes32(string.concat(base, ".poRef"));
        inv.documentHash = _bytes32(string.concat(base, ".documentHash"));
        inv.replaces = _bytes32(string.concat(base, ".replaces"));
        uint256 count = _uint(string.concat(base, ".earlyPayCount"));
        inv.earlyPay = new EarlyPayTier[](count);
        for (uint256 i; i < count; ++i) {
            string memory tier = string.concat(base, ".earlyPay[", vm.toString(i), "]");
            inv.earlyPay[i] = EarlyPayTier({
                payBy: uint64(_uint(string.concat(tier, ".payBy"))),
                discountBps: uint16(_uint(string.concat(tier, ".discountBps")))
            });
        }
    }

    function _offer() internal view returns (EarlyPayOffer memory) {
        return EarlyPayOffer({
            fingerprint: _bytes32(".messages.offer.message.fingerprint"),
            discountBps: uint16(_uint(".messages.offer.message.discountBps")),
            validUntil: uint64(_uint(".messages.offer.message.validUntil"))
        });
    }

    function _label(string memory name) internal pure returns (bytes32) {
        return keccak256(bytes(string.concat("symbolon.vectors.", name)));
    }

    function _labelAddress(string memory name) internal pure returns (address) {
        return address(uint160(uint256(_label(name))));
    }

    function _key(string memory name) internal pure returns (uint256) {
        return uint256(_label(name));
    }

    function _uint(string memory path) internal view returns (uint256) {
        return vm.parseJsonUint(json, path);
    }

    function _bytes32(string memory path) internal view returns (bytes32) {
        return vm.parseJsonBytes32(json, path);
    }

    function _address(string memory path) internal view returns (address) {
        return vm.parseJsonAddress(json, path);
    }
}
